### ISSUE TITLE
Decouple existing worker logic from FNS as a seperate deployable component

### ISSUE THREAD

**Issue by m4sterchain** [apache/incubator-teaclave#115]
Service providers need customized workers in different security levels. Currently all existing workers are running inside the FNS process with limited flexibility. 
We can decouple the worker logic from FNS as a separate deployable component, and make workflow as follows:
- Worker can only communicate with FNS during its lifetime
- Worker instances registered to FNS upon launch
- Worker instances talks to FNS actively for getting task info, running tasks and updating its status 
- FNS manages all registered workers for load balancing and status tracking

**Comment by mssun** [comment]
execution service, worker, and function as been separated.
