### ISSUE TITLE
Contributors meetup: call for participants

### ISSUE THREAD

**Issue by mssun** [apache/incubator-teaclave#122]
Hi folks, recently I posted an outline of features and components we are missing towards a first public release (#121). Therefore, it's a good time to propose a meetup in recent days to discuss some of the details in the outline. I think this is a good way to align with the project roadmap for all contributors and then we can focus on some core building blocks.

I don't have a specific date and time right now, but I'd like to see responses of the community. Also, I think an online meetup is more approachable since we don't have a very large community at this stage.

So, if you are interested in the topics, please feel free to reply this thread to discuss topics, date and time here. Thank you!

**Comment by hi-T0day** [comment]
+1. Looking forward to this meetup. Any date and time is ok for me!

**Comment by mssun** [comment]
Thanks @hi-T0day. Since you are in the Beijing time zone, I'll try to schedule a time which is convenient for all people.

**Comment by dingelish** [comment]
weekend is good to me

**Comment by m4sterchain** [comment]
A Friday or Saturday evening (PST) sounds good to me.

**Comment by m4sterchain** [comment]
Any potential contributor is welcomed. We will also highlight some beginner issues good for a initial contribution.

**Comment by jvz** [comment]
FYI, this type of thing makes more sense to discuss on the mailing list directly.

**Comment by mssun** [comment]
Good suggestion, @jandrunas. The dev list is a bit overloaded with gitbox messages. I'll figure out a better way for the messages.

**Comment by jvz** [comment]
We can set up a notifications mailing list for gitbox messages.

**Comment by mssun** [comment]
Sure! I'll submit a ticket to the infra team.

**Comment by litongxin1991** [comment]
Friday evening or weekend is good to me.

**Comment by rdzhou** [comment]
Friday evening or weekend is fine for me.

**Comment by mssun** [comment]
I'm closing this issue. Will create a new one if we are ready for organizing an online meetup. Thanks.
