### ISSUE TITLE
During installation,it fail to check SGX sdk version.

### ISSUE THREAD

**Issue by xinuo** [apache/incubator-teaclave#299]
When I follow ReadMe.md ,
`
docker run --rm -v $(pwd):/teaclave -w /teaclave   -it teaclave/teaclave-build-ubuntu-1804-sgx-2.9:latest    bash -c ". /root/.cargo/env && \
     mkdir -p build && cd build && \
     cmake -DTEST_MODE=ON -DSGX_SIM_MODE=ON .. && \
     make --trace"
`
and it show:
`
CMake Error at CMakeLists.txt:12 (message):
Intel SGX SDK (version 2.9.1) is not found or version not matched.
`
when i saw CMakeLists.txt line 12 ,it check the sgx sdk version.
And in my host,it already install the sgx sdk version 2.9.1.But in the docker image(teaclave-build-ubuntu-1804-sgx-2.9),i think it is not install the sdk.
So,if i should install the sdk in the docker image?

**Comment by mssun** [comment]
#298 has fixeed this issue, but not merged yet.

**Comment by xinuo** [comment]
> #298 has fixeed this issue, but not merged yet.

Oh thanks.
I saw the contributers are working in baidu . So can i get some contact such like wechat or qq group?

**Comment by mssun** [comment]
Sure. You can drop me an email (mssun at apache dot org), though, it's encouraged to discuss in an open way (e.g., in GitHub issues or mailing list) :)

**Comment by xinuo** [comment]
OK.THANKS.
