### ISSUE TITLE
How to load secrets into teaclave and train a gbdt model

### ISSUE THREAD

**Issue by czzmmc** [apache/incubator-teaclave#308]
Hi, 
After some effort, I got "Hello teaclave" message by running buitin_echo.py and mesapy_echo.py with **HW** mode! That is amazing! And I wanna go further. I'm going to train a gbdt model at my next step. Here, I meet my first question, which is how I can put my secret data files into teaclave. And I also need the my data encrypted before it is loaded into  gbdt model. BTW, do u guys have the docs about registering my own customized functions?

**Comment by mssun** [comment]
For now, you can see our end to end test for reference: https://github.com/apache/incubator-teaclave/blob/master/tests/functional/enclave/src/end_to_end/builtin_gbdt_train.rs.

More examples and docs will be updated in these days. Stay tuned.

Also, if you'd like to contribute, I'll be more than happy.

**Comment by czzmmc** [comment]
@mssun I've already finished the builtin-gbdt-train script, can I do a pull request and upload my code?

**Comment by mssun** [comment]
Great! Yes, you can submit a PR. Thank you so much.

**Comment by mssun** [comment]
#319 has been merged. Issue closed. Thanks!
