### ISSUE TITLE
Be stuck with registering input file when writing builtin-gbdt-train python script

### ISSUE THREAD

**Issue by czzmmc** [apache/incubator-teaclave#314]
Hi, 
I'm writing builtin-gbdt-train python sample script. I got a problem about rewrite the registering input and output files. I imitated the code like register_function like making a RegisterInputFileRequest class and so on, but I invalid request error. Here is my code:

def register_input_file(self):
        url = "http://localhost:6789/fixtures/functions/gbdt_training/train.enc"
        cmac = "881adca6b0524472da0a9d0bb02b9af9"
        crypto_info = "0000000000000000"
        request = RegisterInputFileRequest(self.metadata, urlparse(url), FileAuthTag(cmac), TeaclaveFile128Key(crypto_info))
        write_message(self.channel, request)
        response = read_message(self.channel)
        return reponse["content"]["data_id"]

**Comment by mssun** [comment]
Hi, thanks! You can enable the log with `RUST_LOG=debug=teaclave` to check the request format is a valid or not by comparing to the Rust's test.

**Comment by mssun** [comment]
#319 has been merged. Issue closed. Thanks!
