### ISSUE TITLE
How to create Functions by useing other language such like Go or Java.

### ISSUE THREAD

**Issue by xinuo** [apache/incubator-teaclave#317]
Hi:
In this project , i had seen the function such like "builtin-echo".It can be find in function/src/echo.rs ,right?
So,if i want to create my function useing other language,must i impl the excutor by useing rust and then create my function?

**Comment by mssun** [comment]
Correct.

Currently, we have two executors:
  - native: native functions implemented in Rust
  - mesapy: python functions

We do have plan to implement other executors to support more languages. E.g., we can implement a webassembly executors in SGX, or we can use some libos-like SGX implementations as executors. But this is a long-term plan, and needs a lot efforts.

**Comment by xinuo** [comment]
Ok,thanks for your reply.
