### ISSUE TITLE
Error: Failed to new the enclave

### ISSUE THREAD

**Issue by romanumero** [apache/incubator-teaclave#346]
Running the command: (cd docker && docker-compose -f docker-compose-ubuntu-1804.yml up --build).  Device/volume mappings have been removed from docker-compose-ubuntu-1804.yml

Results in the error:

Successfully tagged docker_teaclave-execution-service:latest
Starting teaclave-authentication-service ... done
Starting teaclave-storage-service        ... done
Starting teaclave-access-control-service ... done
Starting teaclave-management-service     ... done
Starting teaclave-scheduler-service      ... done
Starting teaclave-execution-service      ... done
Starting teaclave-frontend-service       ... done
Attaching to teaclave-authentication-service, teaclave-access-control-service, teaclave-storage-service, teaclave-scheduler-service, teaclave-execution-service, teaclave-management-service, teaclave-frontend-service
teaclave-authentication-service    | Error: Failed to new the enclave.
teaclave-authentication-service    | 
teaclave-authentication-service    | Caused by:
teaclave-authentication-service    |     SgxError
teaclave-access-control-service    | Error: Failed to new the enclave.
teaclave-access-control-service    | 
teaclave-access-control-service    | Caused by:
teaclave-access-control-service    |     SgxError
teaclave-execution-service         | Error: Failed to new the enclave.
teaclave-execution-service         | 
teaclave-execution-service         | Caused by:
teaclave-execution-service         |     SgxError
teaclave-access-control-service exited with code 1
teaclave-execution-service exited with code 1
teaclave-scheduler-service         | Error: Failed to new the enclave.
teaclave-scheduler-service         | 
teaclave-scheduler-service         | Caused by:
teaclave-scheduler-service         |     SgxError
teaclave-management-service        | Error: Failed to new the enclave.
teaclave-management-service        | 
teaclave-management-service        | Caused by:
teaclave-management-service        |     SgxError
teaclave-storage-service           | Error: Failed to new the enclave.
teaclave-storage-service           | 
teaclave-storage-service           | Caused by:
teaclave-storage-service           |     SgxError
teaclave-scheduler-service exited with code 1
teaclave-management-service exited with code 1
teaclave-storage-service exited with code 1
teaclave-frontend-service          | Error: Failed to new the enclave.
teaclave-frontend-service          | 
teaclave-frontend-service          | Caused by:
teaclave-frontend-service          |     SgxError
teaclave-authentication-service exited with code 1
teaclave-frontend-service exited with code 1

OS :Ubuntu 18.04 64-bit
CPU: 3.1 GHz Intel ® Xeon ® Platinum 8269 (Cascade Lake) 
Cloud Provider: Alibaba Cloud (ecs.hfr6); SGX enabled

**Comment by mssun** [comment]
Thanks for the report.

If you want to use in the simulation mode, please configure with cmake `-DSGX_SIM_MODE=ON` when building the platform. Otherwise, you don't have to remove SGX device mapping in the docker compose file.

Seems that you built the platform in hardware mode, but removed the essential device mappings of SGX from the docker container. That's why you got the `SgxError` when start an SGX enclave (in hardware mode).

**Comment by romanumero** [comment]
This worked! Thanks
