### ISSUE TITLE
Could teaclave be used to protect a custom algorithm?

### ISSUE THREAD

**Issue by welaunchcn** [apache/incubator-teaclave#358]
Instead of protecting private data/model, I'm wondering, could teaclave be used to protect custom proprietary algorithm that runs on 3rd party controlled environment? If yes, are there any examples demostrating such usage?

**Comment by mssun** [comment]
Yes, definitely.

We have two typical function executors: Python script executor (language interpreter) and built-in function executor (native function). These should be discussed separately.

For the Python executor, basically, a python script (which implement the proprietary algorithm) is treated as a secret data and executed at runtime. In this case, 3rd party (i.e., service provider) does not know the function.

For built-in functions, the code (e.g., proprietary algorithm implementations) is compiled into the execution service. To protect this kind of functions, we can utilize the Intel PCL (Protected Code Loader) feature which is intended to protect Intellectual Property (IP) within the code for Intel SGX enclave applications [1]. We also have sample code using our Rust SGX SDK. Therefore, to integrate this method to the Teaclave platform, we can make some changes on the execution service enclave to support PCL.

- [1] https://github.com/intel/linux-sgx/tree/master/SampleCode/SampleEnclavePCL/
- [2] https://github.com/apache/incubator-teaclave-sgx-sdk/tree/master/samplecode/pcl
