### ISSUE TITLE
about write a new function with python

### ISSUE THREAD

**Issue by gaojunjie03** [apache/incubator-teaclave#363]
the mesapy_echo_payload.py is too easy , how can i write a python function just like private_join_and_compute.rs？  private_join_and_compute.rs more in line with the actual case ,but 
But learning rust is too expensive

**Comment by mssun** [comment]
Thanks, that's a good suggestion! We had a more complex example of implementing a logistic regression with Python in our previous legacy version (https://github.com/apache/incubator-teaclave/blob/legacy/examples/py_logistic_reg/payload.py). If you have interest to contribute, I can help you to migrate this function to our current platform as an example.

**Comment by gaojunjie03** [comment]
> Thanks, that's a good suggestion! We had a more complex example of implementing a logistic regression with Python in our previous legacy version (https://github.com/apache/incubator-teaclave/blob/legacy/examples/py_logistic_reg/payload.py). If you have interest to contribute, I can help you to migrate this function to our current platform as an example.

I'll learn teacraft first . 
i have anthor question : when i finish install teaclave  in simulation mode, i can not find the The Teaclave command line tool (teaclave_cli) , where is it ?

**Comment by mssun** [comment]
After building the platform, all compilation output will be copied to the `release/` directory. The CLI will be at `release/cli/teaclave_cli`.

**Comment by gaojunjie03** [comment]
> After building the platform, all compilation output will be copied to the `release/` directory. The CLI will be at `release/cli/teaclave_cli`.

ok  find it.
but....
`./teaclave_cli: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`
the release/lib is blank

**Comment by mssun** [comment]
Please install the openssl library: `sudo apt-get install libssl-dev` (for Ubuntu).

**Comment by mssun** [comment]
Thanks to @GeminiCarrie, a PR (0316757e2dfe748185b84d1bff5ae04701b46c8f) of an example on using Python to implement logistic regression has been merged. Please check it out. Thanks.

**Comment by mssun** [comment]
Tutorial on writing functions in Python is also added: https://teaclave.apache.org/docs/functions-in-python/.

I think this issue can be closed. Thanks!
