### ISSUE TITLE
invoke builtin_private_join_and_compute.py error (in simulation mode)

### ISSUE THREAD

**Issue by gaojunjie03** [apache/incubator-teaclave#366]
![image](https://user-images.githubusercontent.com/30582212/85241397-3d88d000-b46e-11ea-892e-1725ebf4bb05.png)

In simulation mode

**Comment by qinkunbao** [comment]
Did you try other examples (e.g., builtin_gbdt_train.py)? Did they work as expected on your machine?

**Comment by gaojunjie03** [comment]
builtin_gbdt_train.py can not work.  
looks like the example with 'register_input_file' can not work . the other can work(mesapy_echo.py、builtin_echo.py 、builtin_online_decrypt.py...)

**Comment by qinkunbao** [comment]
OK. Thanks for the information. Could you please type `make run-tests` or `make run-examples` 
after you build the project?

**Comment by gaojunjie03** [comment]
make run-tests work。  i use the local file "file://" to register_input_file and register_output_file. is that a problem ?

**Comment by mssun** [comment]
I saw an "ocall error" in the response. Maybe this is from the file agent. Since you are saying about using `file://` scheme, I guess this is because your registered file does not exist on the file system of the execution service.

**Comment by gaojunjie03** [comment]
It exists.

**Comment by gaojunjie03** [comment]
> I saw an "ocall error" in the response. Maybe this is from the file agent. Since you are saying about using `file://` scheme, I guess this is because your registered file does not exist on the file system of the execution service.


It exists in the local system

**Comment by mssun** [comment]
Can you run the service with `RUST_LOG=teaclave=debug` env vars and paste the log here? Thanks.

**Comment by gaojunjie03** [comment]
![image](https://user-images.githubusercontent.com/30582212/85246180-82b3fe80-b47c-11ea-957d-e905d762fd58.png)
It's really a non-existent error.  but It exists in the local system
![image](https://user-images.githubusercontent.com/30582212/85246318-e807ef80-b47c-11ea-8600-59736bd47495.png)

**Comment by mssun** [comment]
If you are using docker, the file should be also in the container of the execution service.

**Comment by gaojunjie03** [comment]
![image](https://user-images.githubusercontent.com/30582212/85258295-d3862000-b499-11ea-9be8-f29d0504f818.png)

![image](https://user-images.githubusercontent.com/30582212/85258315-e4369600-b499-11ea-92c1-8f00bf174031.png)

but 

![image](https://user-images.githubusercontent.com/30582212/85258232-b2bdca80-b499-11ea-848b-467665429deb.png)

**Comment by mssun** [comment]
From your previous screenshots of the log, I can see that you are using `docker-compose` to start the services. This command will launch services in different container with isolated file system, i.e., the execution service does not see files in your local file system. If that's the case, please use shared volume in docker with the host and preserve the same path. Or, do not run services in containers separated with the host file system. Thanks.

**Comment by gaojunjie03** [comment]
> From your previous screenshots of the log, I can see that you are using `docker-compose` to start the services. This command will launch services in different container with isolated file system, i.e., the execution service does not see files in your local file system. If that's the case, please use shared volume in docker with the host and preserve the same path. Or, do not run services in containers separated with the host file system. Thanks.

As for the error "convert: failed to open SRC file", I read the source code of teaclave and found that the error was reported when reading outputFile. So I don't register outputFile anymore, just register inputfile. In this case, I can run through the python I wrote and read the data of inputfile normally. However, if I register outputFile, this error will be reported. This outputFile should also exist in teaclave_ execution_service docker container ?

**Comment by mssun** [comment]
Hi, any update on this issue?

**Comment by gaojunjie03** [comment]
> Hi, any update on this issue?

you can close this one

**Comment by mssun** [comment]
Closed.
