### ISSUE TITLE
Is there any best practice to debug builtin function

### ISSUE THREAD

**Issue by yc-huang** [apache/incubator-teaclave#371]
I'm trying to add some new builtin functions, but found it's very time costy to debug; I'm wondering if there's some suggestions on:
1. After mading some changes to the builtin function/executor code, what's the fatest way to re-compile/deploy those changes?
2. What's the best way to log out some debug informations in my builtin functions? 

Thanks,
YC

**Comment by mssun** [comment]
1. I suggest to compile (`make teaclave_unit_tests`) and run (`make run-unit-tests`) unit tests. You can see other builtin function implementations.
2. You can use `log::debug!()`. Then run services or tests with `RUST_LOG=teaclave=debug` env set.

**Comment by mssun** [comment]
You can find more about our build system in this doc: https://teaclave.apache.org/docs/build-system/

**Comment by mssun** [comment]
I'm closing this issue. Feel free to reopen or create a new one if you have further questions. Thanks.
