### ISSUE TITLE
start service error

### ISSUE THREAD

**Issue by gaojunjie03** [apache/incubator-teaclave#373]
docker-compose -f docker-compose-ubuntu-1804.yml up --build

![image](https://user-images.githubusercontent.com/30582212/85995064-7a396600-ba30-11ea-988d-e2938d9c31ab.png)

**Comment by mssun** [comment]
There is something wrong with your SGX environment. Please check if the SGX device (`/dev/isgx`) still exists.

Also, I'll come up a fix to provide more information on the error.

**Comment by gaojunjie03** [comment]
> There is something wrong with your SGX environment. Please check if the SGX device (`/dev/isgx`) still exists.
> 
> Also, I'll come up a fix to provide more information on the error.

The SGX environment and teaclave of the server were running normally. Later, after the server was shut down and restarted, the error unable to find "/dev/ isgx" was reported when starting teaclave. Then, I installed SGX_driver again, there is the file "/dev/isgx", and then starting teaclave will report an error as shown in the figure

**Comment by mssun** [comment]
Also, try to restart the AESM daemon which helps to manage architectural enclaves : `sudo systemctl restart aesmd`.

**Comment by gaojunjie03** [comment]
> sudo systemctl restart aesmd

it work. thanks
but next time when i reboot the system.  
i have to continue to reload SGX_ Driver and restart aesmd?

**Comment by mssun** [comment]
The main reason is that the kernel may be upgraded when you reboot the system. You can setup your Linux distro to manually upgrade kernel.

**Comment by mssun** [comment]
I think this issue has been solved. Closed.

**Comment by mssun** [comment]
Hi, #375 is merged. You will see more error type on SGX related errors. Thanks.
