### ISSUE TITLE
start teaclave services error 2

### ISSUE THREAD

**Issue by gaojunjie03** [apache/incubator-teaclave#376]
reboot kernel
this time no more sgx error
but 
it looks like no communication between services .
After executing the start command many times, it is still reported that there is no communication between services
![image](https://user-images.githubusercontent.com/30582212/86222921-784ede80-bbb9-11ea-97ba-f29717f65cbf.png)

**Comment by gaojunjie03** [comment]
It's not until you restart it many times. maybe got luck?....Is the service unstable?

**Comment by mssun** [comment]
Can you run with debug log enabled (set  the`RUST_LOG=teaclave=debug` env var)? Thanks.

**Comment by gaojunjie03** [comment]
Restart the system again, and then restart teaclave to start normally. Maybe there is something wrong with the operating system. Next time something goes wrong, I'll take a screenshot, thanks
