### ISSUE TITLE
远程稍大文件（50）下载到

### ISSUE THREAD

**Issue by ly137062117** [apache/incubator-teaclave#386]
在execution service 执行任务时，下载的远程文件，通过docker查看，发现sha256sum (tmp文件地址)和sha256sum(我们注册的文件地址)，其结果不一样，runtime.open_input()出现报错Err(Unknown error: 28676 (os error: 28676))。是否是文件下载过程中出现了损坏？

docker中文件进行sha256：
sha256sum Bob_1000.enc
eb11d658c25c2cf0bdf08135ac5af769b76e6adaed60152c1af57885ab66b11f

外部文件进行sha256：
sha256sum Bob_1000.enc
8cc9b09a3d2a0e62a096c592600114f1b1ba667f4d75085df1d5420dbb04bfc8

**Comment by mssun** [comment]
Closed. Duplicated with #387.
