### ISSUE TITLE
关于数据文件加密解密的问题

### ISSUE THREAD

**Issue by gaojunjie03** [apache/incubator-teaclave#400]
现在我已知的数据文件加密解密是通过./teaclave-cli encrypt/decrypt来生成的，也就是我其他方的数据文件必须得拷贝到teaclave所在服务器上才能进行加密和解密。
现在有个问题就是我的数据文件明文可能并不想直接拷贝到teaclave所在服务器上进行解密，因为个人隐私问题。是否能提供这种功能？
如：./teaclave_cli encrypt --algorithm teaclave-file-128 --input-file http://192.168.4.143:8888/teaclave/guest_student_data.csv --key 00000000000000000000000000000000 --output-file http://192.168.4.143:8888/teaclave/guest_student_data_enc.csv -c
通过http连接....
或者是能否介绍下如何用java代码或者其他语言去实现teaclave-file-128算法？这样我可以单独把这个算法抽取出来放到其他机器上单独进行数据文件的加密和解密呢？

**Comment by gaojunjie03** [comment]
或者是否可以单独编译teaclave_cli？

**Comment by qinkunbao** [comment]
可以单独编译teaclave_cli
`$ cd cli`
`$ cargo build`

**Comment by gaojunjie03** [comment]
> 可以单独编译teaclave_cli
> `$ cd cli`
> `$ cargo build`

可以！ 感谢

**Comment by teaclave-archiver** [comment]
Please read our doc on the build system for more advanced building usages.
Thanks.

https://github.com/apache/incubator-teaclave/blob/master/docs/build-system.md
