### ISSUE TITLE
启动服务报错

### ISSUE THREAD

**Issue by gaojunjie03** [apache/incubator-teaclave#403]
非Simulation Mode

![image](https://user-images.githubusercontent.com/30582212/89489325-c8cee280-d7dc-11ea-85f5-38ee3217fefe.png)

![image](https://user-images.githubusercontent.com/30582212/89489359-e0a66680-d7dc-11ea-97ce-37bc0e45f370.png)

![image](https://user-images.githubusercontent.com/30582212/89489365-e56b1a80-d7dc-11ea-9e05-77328ba4687e.png)

![image](https://user-images.githubusercontent.com/30582212/89489376-ebf99200-d7dc-11ea-9fe0-9be0dea07c3a.png)

Failed to start the service: TLS connection error.

**Comment by mssun** [comment]
There are two places which may report this error:

```
 config
        .root_store
        .add_pem_file(&mut DCAP_ROOT_CA_CERT.to_string().as_bytes())
        .map_err(|_| AttestationServiceError::TlsError)?;
```

and
 
```
let mut stream = new_tls_stream(url).map_err(|_| AttestationServiceError::TlsError)?;
```

That is to say, please check the DCAP_ROOT_CA_CERT file or attestation service connectivity.

**Comment by mssun** [comment]
Any update on this issue?

**Comment by gaojunjie03** [comment]
no. u can close this one




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mingshen Sun"<notifications@github.com&gt;; 
发送时间: 2020年8月11日(星期二) 上午10:28
收件人: "apache/incubator-teaclave"<incubator-teaclave@noreply.github.com&gt;; 
抄送: "Gjj."<gaojunjie03@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [apache/incubator-teaclave] 启动服务报错 (#403)





 
Any update on this issue?
