### ISSUE TITLE
About teaclave-file-128 encryption algorithm error

### ISSUE THREAD

**Issue by hoshinoko** [apache/incubator-teaclave#404]
There is no problem with using teaclave-file-128 to encrypt and decrypt data in cli, but when I use teaclave-file-128 to run in Simulation Mode, I found that the key can only take a number less than 2 digits. If it exceeds, an error will occur. What format is the key of teaclave-file-128?

![Q 7J~VRT$ 4BLG9)H8DP11H](https://user-images.githubusercontent.com/32092170/89886098-a8e55780-dbfe-11ea-9e4a-9d634ecc8e57.png)
key：000...0001234

![528d027737e252cc330d8120da95e9d](https://user-images.githubusercontent.com/32092170/89886240-e1853100-dbfe-11ea-8741-56e79c8135ba.png)
key：000...0000004

**Comment by mssun** [comment]
Thanks for your report.

For CLI, the key is in hex format, while in Python SDK, key is in binary array.

`00000000000000000000000000001234` should be `[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x12, 0x34]`.

**Comment by mssun** [comment]
Since there is no update on this issue, I'm closing it. Feel free to reopen if you think it's still valid. Thanks.
