### ISSUE TITLE
about sql capability of trusted computing scripts

### ISSUE THREAD

**Issue by gaojunjie03** [apache/incubator-teaclave#405]
First of all, there is a requirement: use SQL ability to fuse multi-party data to get a result set output, such as the personnel financial data of Party A and the personnel consumption data of Party B, and finally fuse the result set of AB and Party B according to the left/right/inner join of SQL and the where condition. I think this requirement can be realized by using Python pandas or sparksql ... , but it is not supported by mesapy.

What is the solution to achieve this effect? If i use rust to develop built-in functions, it will work?
If rust can be implemented, what libraries can be used to implement rust? I haven't written about rust

**Comment by mssun** [comment]
Sorry, we do not support the libraries you mentioned for data analytics. However, you can write you own function to achieve similar functionalities.

BTW, Apache Arrow's Rust implementation looks promising [1]. I hope someone may help and find out if it works for Teaclave.

- [1] https://github.com/apache/arrow/tree/master/rust

**Comment by gaojunjie03** [comment]
ok thank. i will check it out.
