### ISSUE TITLE
memory allocation of .....failed

### ISSUE THREAD

**Issue by gaojunjie03** [apache/incubator-teaclave#419]
![image](https://user-images.githubusercontent.com/30582212/92670821-6d49c480-f347-11ea-9cf5-168af10e373a.png)

**Comment by mssun** [comment]
Please change the pre-defined heap size in the `Enclave.config.xml` files. You can find it in each service's enclave directory. (e.g., `services/execution/enclave/Enclave.config.xml`)

**Comment by gaojunjie03** [comment]
> services/execution/enclave/Enclave.config.xml

I changed it to look like this

`<EnclaveConfiguration>
  <ProdID>0</ProdID>
  <ISVSVN>0</ISVSVN>
  <StackMaxSize>0x2000000</StackMaxSize> 
  <HeapMaxSize>0x300000000</HeapMaxSize> 
  <TCSNum>22</TCSNum>
  <TCSPolicy>0</TCSPolicy>
  <DisableDebug>0</DisableDebug>
  <MiscSelect>0</MiscSelect>
  <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>`

and restart teacalve, it still reports the same error and kills the executionservice

There are various array loops in my code, and the total amount of data is about 50W

**Comment by gaojunjie03** [comment]
I only modified the Enclave.config.xml of executionservice, it need all services to be modified?

**Comment by gaojunjie03** [comment]
not work.  
After modifying this file, it is executed 
`docker-compose -f docker-compose-ubuntu-1804.yml up --build` ？

**Comment by gaojunjie03** [comment]
emm....  I have to re install and compile teaclave to work

I hope it will work if you restart it
