### ISSUE TITLE
Is task execution concurrent?

### ISSUE THREAD

**Issue by gaojunjie03** [apache/incubator-teaclave#425]
Now I have a task that takes a long time to execute. If I submit other tasks that do not take a long time, they will affect each other. The task that was not executed for a long time will take a long time to complete
So is there a configuration to configure concurrent execution of tasks?

**Comment by mssun** [comment]
You can start more execution services, that is to say, providing more function workers.

**Comment by gaojunjie03** [comment]
> services

ok  i'll try

**Comment by gaojunjie03** [comment]
> You can start more execution services, that is to say, providing more function workers.

Is to add another teaclave execution service = = > teaclave-execution-service2 （expose:17771） in docker-compose-ubuntu-1804.yml file  。

Then 
`docker-compose -f docker-compose-ubuntu-1804.yml start teaclave-execution-service2`？

**Comment by gaojunjie03** [comment]
got it
