### ISSUE TITLE
builtin function question

### ISSUE THREAD

**Issue by gaojunjie03** [apache/incubator-teaclave#427]
I added a built-in function that requires a third-party library, but I reported an error when compiling.

![image](https://user-images.githubusercontent.com/30582212/97081619-1e759700-1636-11eb-9aaf-c43a7ca24f76.png)

This bag is in https://crates.io/ It exists

**Comment by mssun** [comment]
In short, you cannot use third-party Rust crates which are not in the `third_party/crates-sgx` directory.

For your case, if you want to use ndarray, you need to vendor ndarray-sgx (https://github.com/mesalock-linux/ndarray-sgx) in the `crates-sgx` directory.

**Comment by gaojunjie03** [comment]
> In short, you cannot use third-party Rust crates which are not in the `third_party/crates-sgx` directory.
> 
> For your case, if you want to use ndarray, you need to vendor ndarray-sgx (https://github.com/mesalock-linux/ndarray-sgx) in the `crates-sgx` directory.

ok i'll try.
Can you provide a document on how to add a third-party library to crates-sgx, because I may need other third-party libraries in the future, which are not available in crates-sgx.

**Comment by mssun** [comment]
Thanks for your suggestion. We will definitely document it when we find out a good workflow for working on third-party SGX crates. Before this, you have to understand our build system in order to include more SGX libraries.
