### ISSUE TITLE
questions about custom Executor 

### ISSUE THREAD

**Issue by gaojunjie03** [apache/incubator-teaclave#430]
now teaclave have builtin and mesapy executor .

I want to customize an executor myself, Does this custom executor need to implement SGX like mesapy to join teaclave?

**Comment by mssun** [comment]
You can implement you own executor.

I don't understand your question. I guess you were asking how to add your executor into the Teaclave execution service. Yes, you can refer to the interfaces of MesaPy and Builtin executors.

**Comment by gaojunjie03** [comment]
My plan now is to write a golang dynamic library, which provides golang computing tasks. Then connect the dynamic library to execution_service (executor), I found that the connection action is in cmake/scripts/sgx_ link_ sign.sh So I add dynamic library connection to this script


![image](https://user-images.githubusercontent.com/30582212/98623613-152f3e80-2347-11eb-9c66-2665c488e13a.png)


the execution of this command was successful

But in the sgx_sign is wrong.

![image](https://user-images.githubusercontent.com/30582212/98623739-4c055480-2347-11eb-955b-622272ee1e4b.png)

Therefore, can only static library link, not dynamic library link?
