### ISSUE TITLE
关于自定义添加外部依赖到crates-io问题

### ISSUE THREAD

**Issue by gaojunjie03** [apache/incubator-teaclave#443]
我添加了一下第三方依赖到crates-io的vendor上，在A服务器编译成功了，然后我提交代码（第三方源）到我的git crates-io仓库中，teaclave主仓库也更新了crates-io。 然后我再另外一台B机器上安装编译teaclave时，发现会出现crates-io中的依赖会出现list checksum的问题 说这个文件期待值是某个hash值  但实际上是这个hash值（.cargo-checksum.json）。
我把A机器上的crates-io整个vendor目录拷贝到B服务器上的crates-io就没问题了。 但是这样再换一台机器安装teaclave还是会出现list checksum的问题。
这个该如何解决呢？

**Comment by mssun** [comment]
你的 submodule 没有 commit？

**Comment by gaojunjie03** [comment]
我是这样提交的，因为其他方案对我无效 所以我采用以下方案，不知是否有问题？
在teaclve主仓库下执行以下：
![image](https://user-images.githubusercontent.com/30582212/102295414-3a3a5100-3f86-11eb-8e0f-88c08d337e65.png)

**Comment by mssun** [comment]
感觉没问题，你能确认一下 pull 下来的 crates-io 的 submodule 是你新的地址么 (https://xxx/crates-io)？
