### ISSUE TITLE
运行builtin_gbdt_train.py出现以下报错，是什么问题呢

### ISSUE THREAD

**Issue by xglreal** [apache/incubator-teaclave#444]
使用模拟模式运行gbdt示例，出现报错
运行命令：$SGX_MODE=SW PYTHONPATH=../../sdk/python python3 builtin_gbdt_train.py 
出现错误：
'result': {'result': {'Err': {'reason': 'ocall error = 1'}}}}
这是什么问题呢？

**Comment by mssun** [comment]
请问你是如何启动 teaclave services 的？

**Comment by xglreal** [comment]
> 请问你是如何启动 teaclave services 的？

 (cd docker && docker-compose -f docker-compose-ubuntu-1804-sgx-sim-mode.yml up --build)

docker-compose启动的

builtin_face_detection.py builtin_online_decrypt.py这些都能运行成功。看了以下差异好像是builtin_face_detection.py builtin_online_decrypt.py直接输出结果，builtin_gbdt_train.py是往链接里写数据？

运行/incubator-teaclave/tests/scripts/simple_http_server.py使链接http://localhost:6789/fixtures/functions/gbdt_training/train.enc能够访问。

**Comment by mssun** [comment]
明白了，这里应该是 execution service 的 docker 无法访问 localhost 这个文件系统才出现的错误。

**Comment by mssun** [comment]
一个解决方法是修改 docker compose 文件：
```patch
diff --git a/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml b/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml
index aa5388d..b0f25aa 100644
--- a/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml
+++ b/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml
@@ -134,6 +134,7 @@ services:
       - teaclave-scheduler-service
     networks:
       internal:
+      fs:

   teaclave-scheduler-service-sgx-sim-mode:
     build:
@@ -157,6 +158,16 @@ services:
     networks:
       internal:

+  teaclave-file-service:
+    image: python:3
+    volumes:
+      - ../tests:/teaclave-file-service
+    working_dir: /teaclave-file-service
+    entrypoint: ./scripts/simple_http_server.py
+    networks:
+      fs:
+
 networks:
   internal:
   api:
+  fs:
```

service 启动后找到  teaclave-file-service 的名字：
```
$ docker ps
docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                               NAMES
8f41f56016d9        python:3                                 "./scripts/simple_ht…"   4 minutes ago       Up 4 minutes        6789/tcp                            docker_teaclave-file-service_1
```

修改在 example 的文件地址为：```http://docker_teaclave-file-service_1:5678/xxxxxx```

**Comment by xglreal** [comment]
ERROR: for docker_teaclave-file-service_1  Cannot start service teaclave-file-service: OCI runtime create failed: container_linux.go:349: starting container process causRecreating teaclave-scheduler-service   ... done
teaclave-execution-service is up-to-date

ERROR: for teaclave-file-service  Cannot start service teaclave-file-service: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./scripts/simple_http_server.py\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.


启动service teaclave-file-service报错？

**Comment by xglreal** [comment]
> 一个解决方法是修改 docker compose 文件：
> 
> ```diff
> diff --git a/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml b/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml
> index aa5388d..b0f25aa 100644
> --- a/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml
> +++ b/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml
> @@ -134,6 +134,7 @@ services:
>        - teaclave-scheduler-service
>      networks:
>        internal:
> +      fs:
> 
>    teaclave-scheduler-service-sgx-sim-mode:
>      build:
> @@ -157,6 +158,16 @@ services:
>      networks:
>        internal:
> 
> +  teaclave-file-service:
> +    image: python:3
> +    volumes:
> +      - ../tests:/teaclave-file-service
> +    working_dir: /teaclave-file-service
> +    entrypoint: ./scripts/simple_http_server.py
> +    networks:
> +      fs:
> +
>  networks:
>    internal:
>    api:
> +  fs:
> ```
> 
> service 启动后找到 teaclave-file-service 的名字：
> 
> ```
> $ docker ps
> docker ps
> CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                               NAMES
> 8f41f56016d9        python:3                                 "./scripts/simple_ht…"   4 minutes ago       Up 4 minutes        6789/tcp                            docker_teaclave-file-service_1
> ```
> 
> 修改在 example 的文件地址为：`http://docker_teaclave-file-service_1:5678/xxxxxx`

ERROR: for docker_teaclave-file-service_1 Cannot start service teaclave-file-service: OCI runtime create failed: container_linux.go:349: starting container process causRecreating teaclave-scheduler-service ... done
teaclave-execution-service is up-to-date

ERROR: for teaclave-file-service Cannot start service teaclave-file-service: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: "./scripts/simple_http_server.py": permission denied": unknown
ERROR: Encountered errors while bringing up the project.

启动service teaclave-file-service报错？

**Comment by xglreal** [comment]
wget http://docker_teaclave-file-service_1:6789
\--2020-12-16 10:22:58--  http://docker_teaclave-file-service_1:6789/
Resolving docker_teaclave-file-service_1 (docker_teaclave-file-service_1)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘docker_teaclave-file-service_1’


docker_teaclave-file-service_1解析不了



镜像
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                               NAMES
03f3fa28793c        docker_teaclave-scheduler-service        "./teaclave_schedule…"   32 minutes ago      Up 32 minutes       17780/tcp                           teaclave-scheduler-service
3ec63834b9d1        python:3                                 "./scripts/simple_ht…"   32 minutes ago      Up 14 minutes                                           docker_teaclave-file-service_1

**Comment by xglreal** [comment]
> 一个解决方法是修改 docker compose 文件：
> 
> ```diff
> diff --git a/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml b/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml
> index aa5388d..b0f25aa 100644
> --- a/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml
> +++ b/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml
> @@ -134,6 +134,7 @@ services:
>        - teaclave-scheduler-service
>      networks:
>        internal:
> +      fs:
> 
>    teaclave-scheduler-service-sgx-sim-mode:
>      build:
> @@ -157,6 +158,16 @@ services:
>      networks:
>        internal:
> 
> +  teaclave-file-service:
> +    image: python:3
> +    volumes:
> +      - ../tests:/teaclave-file-service
> +    working_dir: /teaclave-file-service
> +    entrypoint: ./scripts/simple_http_server.py
> +    networks:
> +      fs:
> +
>  networks:
>    internal:
>    api:
> +  fs:
> ```
> 
> service 启动后找到 teaclave-file-service 的名字：
> 
> ```
> $ docker ps
> docker ps
> CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                               NAMES
> 8f41f56016d9        python:3                                 "./scripts/simple_ht…"   4 minutes ago       Up 4 minutes        6789/tcp                            docker_teaclave-file-service_1
> ```
> 
> 修改在 example 的文件地址为：`http://docker_teaclave-file-service_1:5678/xxxxxx`

wget http://docker_teaclave-file-service_1:6789
--2020-12-16 10:22:58-- http://docker_teaclave-file-service_1:6789/
Resolving docker_teaclave-file-service_1 (docker_teaclave-file-service_1)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘docker_teaclave-file-service_1’

docker_teaclave-file-service_1解析不了

镜像
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
03f3fa28793c docker_teaclave-scheduler-service "./teaclave_schedule…" 32 minutes ago Up 32 minutes 17780/tcp teaclave-scheduler-service
3ec63834b9d1 python:3 "./scripts/simple_ht…" 32 minutes ago Up 14 minutes docker_teaclave-file-service_1

**Comment by xglreal** [comment]
> 一个解决方法是修改 docker compose 文件：
> 
> ```diff
> diff --git a/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml b/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml
> index aa5388d..b0f25aa 100644
> --- a/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml
> +++ b/docker/docker-compose-ubuntu-1804-sgx-sim-mode.yml
> @@ -134,6 +134,7 @@ services:
>        - teaclave-scheduler-service
>      networks:
>        internal:
> +      fs:
> 
>    teaclave-scheduler-service-sgx-sim-mode:
>      build:
> @@ -157,6 +158,16 @@ services:
>      networks:
>        internal:
> 
> +  teaclave-file-service:
> +    image: python:3
> +    volumes:
> +      - ../tests:/teaclave-file-service
> +    working_dir: /teaclave-file-service
> +    entrypoint: ./scripts/simple_http_server.py
> +    networks:
> +      fs:
> +
>  networks:
>    internal:
>    api:
> +  fs:
> ```
> 
> service 启动后找到 teaclave-file-service 的名字：
> 
> ```
> $ docker ps
> docker ps
> CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                               NAMES
> 8f41f56016d9        python:3                                 "./scripts/simple_ht…"   4 minutes ago       Up 4 minutes        6789/tcp                            docker_teaclave-file-service_1
> ```
> 
> 修改在 example 的文件地址为：`http://docker_teaclave-file-service_1:5678/xxxxxx`


按照你的方法配置了，有问题
wget http://docker_teaclave-file-service_1:6789
--2020-12-16 10:22:58-- http://docker_teaclave-file-service_1:6789/
Resolving docker_teaclave-file-service_1 (docker_teaclave-file-service_1)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘docker_teaclave-file-service_1’

docker_teaclave-file-service_1解析不了

镜像
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
03f3fa28793c docker_teaclave-scheduler-service "./teaclave_schedule…" 32 minutes ago Up 32 minutes 17780/tcp teaclave-scheduler-service
3ec63834b9d1 python:3 "./scripts/simple_ht…" 32 minutes ago Up 14 minutes docker_teaclave-file-service_1

**Comment by mssun** [comment]
> wget http://docker_teaclave-file-service_1:6789
--2020-12-16 10:22:58-- http://docker_teaclave-file-service_1:6789/
Resolving docker_teaclave-file-service_1 (docker_teaclave-file-service_1)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘docker_teaclave-file-service_1’

docker_teaclave-file-service_1解析不了

这个是在 execution service 的 docker container 里才能 resolve 的域名。通过 fs 这个 network 连接。

**Comment by xglreal** [comment]
> > wget http://docker_teaclave-file-service_1:6789
> > --2020-12-16 10:22:58-- http://docker_teaclave-file-service_1:6789/
> > Resolving docker_teaclave-file-service_1 (docker_teaclave-file-service_1)... failed: Temporary failure in name resolution.
> > wget: unable to resolve host address ‘docker_teaclave-file-service_1’
> 
> docker_teaclave-file-service_1解析不了
> 
> 这个是在 execution service 的 docker container 里才能 resolve 的域名。通过 fs 这个 network 连接。


为什么把localhost改成公网ip也不行呢？一样的报错信息

**Comment by xglreal** [comment]
> > wget http://docker_teaclave-file-service_1:6789
> > --2020-12-16 10:22:58-- http://docker_teaclave-file-service_1:6789/
> > Resolving docker_teaclave-file-service_1 (docker_teaclave-file-service_1)... failed: Temporary failure in name resolution.
> > wget: unable to resolve host address ‘docker_teaclave-file-service_1’
> 
> docker_teaclave-file-service_1解析不了
> 
> 这个是在 execution service 的 docker container 里才能 resolve 的域名。通过 fs 这个 network 连接。

谢谢，问题已解决。
