### ISSUE TITLE
worker含义

### ISSUE THREAD

**Issue by xglreal** [apache/incubator-teaclave#450]
+-----------------------------------+
    |        Execution Service               |
    |  +-----------------------------+  |
    |  |            Worker                     |  |
    |  |  +----------+  +---------+   |  |
    |  |  | Executor |  | Runtime   |  |  |
    |  |  +----------+  +---------+   |  |
    |  +-----------------------------+  |
    +-----------------------------------+

请问下：
worker是具体对应到了具体的sgx硬件了吗？
一个Execution Service可以分配多个sgx？
然后runtime是什么含义？我看可以指定default, raw-io，这两个有什么区别吗？
提交到gsx是以什么方式提交的？rust代码吗？各方数据文件是以数据链接+key的方式还是直接加密的数据文件传入的？

**Comment by gaojunjie03** [comment]
> 提交到gsx是以什么方式提

1/2、实际上整个execution-service（enclave端）服务已经在sgx环境上跑了，所以整个execution-service（enclave端）是在可信环境上执行
3、runtime的作用就是用来给你的文件数据进行解密获取，加密写出。比如mesapy的with teaclave_open("label","rb") as f: 最终会调用runtime的open_input获取解密后的数据，with teaclave_open("label","wb") as f: 则最终调用runtime的create_output将要写入的数据进行加密然后写到文件
default 是默认的runtime用于生产环境，raw-io是测试用的runtime
4、以execution-service为例（其它的服务都是同样的操作），首先将edl文件生成一个.o的执行文件，然后利用这个.o的执行文件与execution-service（enclave）编译生成的静态库、mesapy的静态库和sgx的一些静态库库一起合并生成一个共享库(so)，然后sgx的sdk对该共享库进行签名生成最终的execution-service.sign.so签名共享库。   最终execution-service（app）端会使用rust-sgx-sdk的api启动该execution-service.sign.so签名共享库。所以整个execution-service(enclave)端是完全在sgx环境下执行的
5、各方数据文件先用cli工具进行加密，然后利用teaclave提供的pythonsdk进行数据的注册，最终写py代码时，with teaclave_open("label","rb") as f: 这个label是你注册数据时的label，runtime会用这个label找到对应的文件链接（因为你已经用pythonsdk进行label和链接密钥cmac等进行注册了），接下来就是3的那个过程
------------------------------------------------------------------------------------------
我是阅读了底层源码给你的解答，我不是作者本人~.~  可能会有些出入，但我觉得大致就是如我所说的那样。  作者如果发现我有回答错误的希望提出解答下

**Comment by gaojunjie03** [comment]
1/2、实际上整个execution-service（enclave端）服务已经在sgx环境上跑了，所以整个execution-service（enclave端）是在可信环境上执行
3、runtime的作用就是用来给你的文件数据进行解密获取，加密写出。比如mesapy的with teaclave_open("label","rb") as f: 最终会调用runtime的open_input获取解密后的数据，with teaclave_open("label","wb") as f: 则最终调用runtime的create_output将要写入的数据进行加密然后写到文件default 是默认的runtime用于生产环境，raw-io是测试用的runtime
4、以execution-service为例（其它的服务都是同样的操作），首先将edl文件生成一个.o的执行文件，然后利用这个.o的执行文件与execution-service（enclave）编译生成的静态库、mesapy的静态库和sgx的一些静态库库一起合并生成一个共享库(so)，然后sgx的sdk对该共享库进行签名生成最终的execution-service.sign.so签名共享库。 最终execution-service（app）端会使用rust-sgx-sdk的api启动该execution-service.sign.so签名共享库。所以整个execution-service(enclave)端是完全在sgx环境下执行的
5、各方数据文件先用cli工具进行加密，然后利用teaclave提供的pythonsdk进行数据的注册，最终写py代码时，with teaclave_open("label","rb") as f: 这个label是你注册数据时的label，runtime会用这个label找到对应的文件链接（因为你已经用pythonsdk进行label和链接密钥cmac等进行注册了），接下来就是3的那个过程


我是阅读了底层源码给你的解答，我不是作者本人~.~ 可能会有些出入，但我觉得大致就是如我所说的那样。 作者如果发现我有回答错误的希望提出解答下

**Comment by mssun** [comment]
@gaojunjie03 多谢你的回答，非常准确。现在文档还不是很完善，阅读代码会更直接一些。

**Comment by xglreal** [comment]
> 1/2、实际上整个execution-service（enclave端）服务已经在sgx环境上跑了，所以整个execution-service（enclave端）是在可信环境上执行
> 3、runtime的作用就是用来给你的文件数据进行解密获取，加密写出。比如mesapy的with teaclave_open("label","rb") as f: 最终会调用runtime的open_input获取解密后的数据，with teaclave_open("label","wb") as f: 则最终调用runtime的create_output将要写入的数据进行加密然后写到文件default 是默认的runtime用于生产环境，raw-io是测试用的runtime
> 4、以execution-service为例（其它的服务都是同样的操作），首先将edl文件生成一个.o的执行文件，然后利用这个.o的执行文件与execution-service（enclave）编译生成的静态库、mesapy的静态库和sgx的一些静态库库一起合并生成一个共享库(so)，然后sgx的sdk对该共享库进行签名生成最终的execution-service.sign.so签名共享库。 最终execution-service（app）端会使用rust-sgx-sdk的api启动该execution-service.sign.so签名共享库。所以整个execution-service(enclave)端是完全在sgx环境下执行的
> 5、各方数据文件先用cli工具进行加密，然后利用teaclave提供的pythonsdk进行数据的注册，最终写py代码时，with teaclave_open("label","rb") as f: 这个label是你注册数据时的label，runtime会用这个label找到对应的文件链接（因为你已经用pythonsdk进行label和链接密钥cmac等进行注册了），接下来就是3的那个过程
> 
> 我是阅读了底层源码给你的解答，我不是作者本人~.~ 可能会有些出入，但我觉得大致就是如我所说的那样。 作者如果发现我有回答错误的希望提出解答下

谢谢解答
