### ISSUE TITLE
关于execution-service服务的问题

### ISSUE THREAD

**Issue by gaojunjie03** [apache/incubator-teaclave#451]
我看到这里的源码
![image](https://user-images.githubusercontent.com/30582212/103389671-3cd2a400-4b4b-11eb-9852-93cb236a1df7.png)
一次只能拉取一个准备执行的任务，这里为什么不能做一次拉取多次任务比如5次，然后5次都是并发执行，然后主线程等待这5次线程执行完毕再循环下一次？
这样看execution-service一次只能执行一个task，这好像效率不是很高。是因为什么不能做并发执行呢？
(当然我知道可以同时启动多个execution-service，这样就可以并发执行多个task，但效率还是远远不够)

**Comment by mssun** [comment]
有一下几个原因：

- SGX EPC 大小受限，多线程不会带来太多的 performance gain
- 线程之间没有内存隔离（进程隔离），不同 task 在同一进程执行可能会带来安全隐患

一台物理机启动多个 execution-service 的方式进行并发执行应该能满足现在的需求。

**Comment by gaojunjie03** [comment]
> 有一下几个原因：
> 
> * SGX EPC 大小受限，多线程不会带来太多的 performance gain
> * 线程之间没有内存隔离（进程隔离），不同 task 在同一进程执行可能会带来安全隐患
> 
> 一台物理机启动多个 execution-service 的方式进行并发执行应该能满足现在的需求。

好的  明白
