### ISSUE TITLE
I a error when use simulate model

### ISSUE THREAD

**Issue by master-davidlee** [apache/incubator-teaclave#461]
I met a error 
![image](https://user-images.githubusercontent.com/49427668/105138662-2c9d5b80-5b30-11eb-8fb5-3c692c99e6cd.png)
and this is my release/services
![image](https://user-images.githubusercontent.com/49427668/105138731-4474df80-5b30-11eb-92df-ab878727b69a.png)
and I successed compiled
![image](https://user-images.githubusercontent.com/49427668/105139407-3c696f80-5b31-11eb-96a2-c40900527e93.png)

_Originally posted by @master-davidlee in https://github.com/apache/incubator-teaclave/issues/437#issuecomment-763385226_

**Comment by mssun** [comment]
See PR #462.

**Comment by master-davidlee** [comment]
Thanks it work
