### ISSUE TITLE
GPG error: The following signatures couldn't be verified

### ISSUE THREAD

**Issue by master-davidlee** [apache/incubator-teaclave#471]
when I run the last  command 
![image](https://user-images.githubusercontent.com/49427668/105863271-adc28a00-602b-11eb-83ef-1d0dfc5c6348.png)
I met an error 
![image](https://user-images.githubusercontent.com/49427668/105863327-bfa42d00-602b-11eb-86fd-9be814479865.png)

**Comment by master-davidlee** [comment]
And I use these 2 steps fixed it 
1. the first step is to take note of the public key, for example, there is the 78BD65473CB3BD13
![image](https://user-images.githubusercontent.com/49427668/105863541-f417e900-602b-11eb-8b12-c5cb368edde7.png)
2. sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys (public_key)
Then it should be fixed

**Comment by mssun** [comment]
I think this command will add the public key of Intel.  `$ wget -qO - https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | sudo apt-key add -` . What did I missing? Any errors when adding the key for you?

**Comment by master-davidlee** [comment]
I remember this command returned OK, but the error still occurred but I have fixed it. Can you take look at the other error#463. It bothers me many days Thanks

**Comment by mssun** [comment]
I believe this issue can be closed. Feel free to reopen it if you need more helps.
