### ISSUE TITLE
Is it possible to run rusty-leveldb on top of teaclave-sgx-sdk

### ISSUE THREAD

**Issue by jyizheng** [apache/incubator-teaclave#513]
I am wondering if it is possible to run rusty-leveldb on top of teaclave-sgx-sdk.
Since teaclave can run rusty-leveldb as its storage service, I guess it should not be very hard to run rusty-leveldb
over teaclave-sgx-sdk directly. I am wondering if there are any steps to follow to port rustly-leveldb to teaclave-sgx-sdk.

Thanks for your help in advance.

**Comment by mssun** [comment]
Yes, absolutely.

Here is an example of how we use `rusty-leveldb` in SGX:

https://github.com/apache/incubator-teaclave/blob/master/services/storage/enclave/Cargo.toml#L36

**Comment by jyizheng** [comment]
@mssun , thank you so much for the pointer. 

I am wondering what sgx sdk, rusty-leveldb is using?

According to the Cargo.toml file, it seems it uses mesalock_sgx, instead of teaclave-sgx-sdk (https://github.com/apache/incubator-teaclave-sgx-sdk), correct?

**Comment by mssun** [comment]
We have ported the `rusty-leveldb` into SGX hosted here: https://github.com/apache/incubator-teaclave/tree/master/common/rusty_leveldb_sgx.

For the SGX SDK, we are using vendored Teaclave SGX SDK version 1.1.2.

> According to the Cargo.toml file, it seems it uses mesalock_sgx, instead of teaclave-sgx-sdk (https://github.com/apache/incubator-teaclave-sgx-sdk), correct?

They are same one actually.

**Comment by jyizheng** [comment]
Thanks for your clarification.

**Comment by mssun** [comment]
I'm closing this issue. Feel free to reopen or create a new one if needed. Thanks!
