### ISSUE TITLE
Python.h not found

### ISSUE THREAD

**Issue by bigdata-memory** [apache/incubator-teaclave#526]
On my system, the following error message shown up when compiling acs_py_enclave.c

`
Scanning dependencies of target pycomponent
[ 34%] Building C object CMakeFiles/pycomponent.dir/intermediate/acs_py_enclave.c.o
/home/gordon/incubator-teaclave/build/intermediate/acs_py_enclave.c:29:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
CMakeFiles/pycomponent.dir/build.make:67: recipe for target 'CMakeFiles/pycomponent.dir/intermediate/acs_py_enclave.c.o' failed
make[2]: *** [CMakeFiles/pycomponent.dir/intermediate/acs_py_enclave.c.o] Error 1
CMakeFiles/Makefile2:720: recipe for target 'CMakeFiles/pycomponent.dir/all' failed
make[1]: *** [CMakeFiles/pycomponent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

My finding is the following script snippet that didn't detect the dependency correctly in file `CMakeLists.txt`, because the package `pypy` also put some header files e.g. `pypy_decl.h` in this folder so we cannot safely say that the `pypy_dev` has got installed if the folder `/usr/lib/pypy/include` exists.
`
if(NOT EXISTS "/usr/lib/pypy/include")
  message(
    FATAL_ERROR
      "pypy development package not found\nFor Ubuntu, please run `apt-get install pypy-dev`"
  )
endif()
`

**Comment by mssun** [comment]
Nice catch! Thanks.

Normally, we use docker container to build Teaclave.

CMakeList may miss some dependency checks.

**Comment by mssun** [comment]
Merged.
