### ISSUE TITLE
A minor typo issue in a DOCS webpage

### ISSUE THREAD

**Issue by bigdata-memory** [apache/incubator-teaclave#528]
There is a minor type issue in a webpage linked by https://teaclave.apache.org/docs/development-tips/
`parth::to::module=level` => `path::to::module=level`

**Comment by mssun** [comment]
Nice catch. This doc is automatically generated from here: https://github.com/apache/incubator-teaclave/blob/master/docs/development-tips.md.

You can quickly fix it accordingly.

**Comment by bigdata-memory** [comment]
Thank you for the hint.
