### ISSUE TITLE
A top-level Cargo.toml for virtual workspaces

### ISSUE THREAD

**Issue by bigdata-memory** [apache/incubator-teaclave#546]
### Motivation & problem statement
The code analyzer cannot correctly identify this rust project and its workspaces corresponding to  each subdirectories.

### Proposed solution
Adding a top-level Cargo.toml, this configures a virtual workspace – a workspace that is only a container for member packages, but does not build a package itself.

See the main [Cargo.toml](https://github.com/SergioBenitez/Rocket/blob/master/Cargo.toml) file of Rocket for a real-world example of a virtual workspace

**Comment by ya0guang** [comment]
The trusted part and untrusted part use different set of crates. So we provide a script to prepare analyzer's essentials. You may check [this doc](https://teaclave.apache.org/docs/development-tips/) and try with the script to see if it can solve your concern.

**Comment by mssun** [comment]
Hi, this is not feasible right now. Teaclave uses two set of Rust dependencies for SGX enclave and untrusted normal world separately. We haven't consolidated these into one. Therefore, we have to compile code in different worlds separately with different `Cargo.toml` files. You can find there here: https://github.com/apache/incubator-teaclave/tree/master/cmake/tomls. Our building system (cmake) will help to switch dependencies when building code for different worlds.

**Comment by bigdata-memory** [comment]
@ya0guang @mssun  Thank you for the clarification. However, I still see some workspaces, e.g. `executor` which didn't get indexed either way because they seems not be included in both Cargo.toml files as workspace members.

**Comment by bigdata-memory** [comment]
The problem solved, thanks.
