### ISSUE TITLE
Cannot build TVM example

### ISSUE THREAD

**Issue by mssun** [apache/incubator-teaclave#547]
CI is broken now as well: https://github.com/apache/incubator-teaclave/runs/3353624057

This is caused by `onnx/models`'s Git LFS quota reached. https://github.com/onnx/models/issues/459

**Comment by ya0guang** [comment]
This error originates [here](https://github.com/apache/incubator-teaclave/blob/master/examples/python/wasm_tvm_mnist_payload/build_lib.py#L37). The file cannot be downloaded when building the library. I'll store the onnx file to the example folder when the it's accessible.

**Comment by mssun** [comment]
The quota issue of `onnx/models` has been fixed.
