### ISSUE TITLE
How to deploy Teaclave on TrustZone platform

### ISSUE THREAD

**Issue by aqinwenky** [apache/incubator-teaclave#551]
I have deployed Teaclave based on Intel SGX and  The example has been successfully run.
I also have deployed Teaclave-trustzon-sdk based on OP-TEE. 
so I‘m wondering if Teaclave can be deployed based on Teaclave-trustzon-sdk? If it can be deployed, how to deploy it?

**Comment by mssun** [comment]
> so I‘m wondering if Teaclave can be deployed based on Teaclave-trustzon-sdk? If it can be deployed, how to deploy it?

No. The current implementation of Teaclave FaaS platform is for Intel SGX.

**Comment by aqinwenky** [comment]
ok，thanks
