### ISSUE TITLE
[Simulation Mode] Bugs in Teaclave Docker Services

### ISSUE THREAD

**Issue by qinkunbao** [apache/incubator-teaclave#562]
I built teaclave in **simulation** mode, following the instruction from https://github.com/apache/incubator-teaclave/blob/master/docs/my-first-function.md

When I tried to launch Teaclave services, I encountered the following error.

```
$ (cd docker && ./run-teaclave-services.sh)
/dev/isgx device detected.
Error: No such volume: aesmd-socket
Cannot find a valid aesm service.
```

**Comment by mssun** [comment]
Should be `./run-teaclave-services.sh -m sim` for simulation mode.

https://github.com/apache/incubator-teaclave/blob/master/docker/run-teaclave-services.sh#L124

**Comment by qinkunbao** [comment]
Thank you! I will update the document later.
