### ISSUE TITLE
[Suggestion] Rename KEYS or keys

### ISSUE THREAD

**Issue by qinkunbao** [apache/incubator-teaclave#567]
Most Unix-style OSs are case-sensitive in file names, meaning that a folder called `KEYs` is different from a file named `keys`.

However, Mac OS is not case-sensitive. So whenever developers clone a new repo, the system will delete the folder `keys`, and a freshly cloned repo may look messy.

**Comment by henrysun007** [comment]
The `keys` folder seems reasonable.  How about renaming the file to, for example, `PGP_KEYS`, "DEVELOPER_KEYS"?
