### ISSUE TITLE
[Website] Incorrect archive link

### ISSUE THREAD

**Issue by bigdata-memory** [apache/incubator-teaclave#599]
There is a minor bug that appears on the `community` webpage.  The following `Archive`  linked to `commit mail-list` not the `dev`
<li><code>dev@teaclave.apache.org</code>: A list for discussion on Teaclave development including design proposal, release
announcements, meetup schedules, and commnity voting, etc.
[<a href="mailto:dev-subscribe@teaclave.apache.org?subject=Subscribe" rel="noreferrer" data-ss1641849516="1">Subscribe</a> | <a href="mailto:dev-unsubscribe@teaclave.apache.org?subject=Unsubscribe" rel="noreferrer" data-ss1641849516="1">Unsubscribe</a> | <a href="https://lists.apache.org/list.html?commits@teaclave.apache.org" target="_blank" rel="noopener noreferrer" data-ss1641849516="1">Archive</a>]</li>

**Comment by mssun** [comment]
Fixed in this commit: https://github.com/apache/incubator-teaclave-website/commit/1921d33ab1cbe52e4a0045cb2200544b010808f2

The updated page will be rendered soon.

**Comment by mssun** [comment]
Fixed and rendered. Thanks!
