### ISSUE TITLE
Upgrade mesatee_utils/protected_fs

### ISSUE THREAD

**Issue by m4sterchain** [apache/incubator-teaclave#60]
We have already got the protected_fs library ready [here](https://github.com/mesalock-linux/protected_fs_rs), which supports running in both sgx and non-sgx environments. It's time to upgrade the existing one in mesatee_utils.

After the upgrade, we can support more customized interface for the ProtectedFile.

**Comment by mssun** [comment]
This issue has been fixed. We maintained our own protected_fs ourselves.
