### ISSUE TITLE
Build error with DCAP = ON

### ISSUE THREAD

**Issue by Lio101** [apache/incubator-teaclave#630]
Hi, 
I am getting error when trying to build Teaclave with DCAP=ON
Platform:  Azure CC VM
OS: Ubuntu 18.04

Error  :
`[ 76%] Built target sgxlib-teaclave_access_control_service
[ 79%] Generating enclave signatures...
[ 79%] Built target update_sig
[ 82%] Building sgxapp-teaclave_frontend_service
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
[ 82%] Built target sgxapp-teaclave_frontend_service
[ 84%] Building sgxapp-teaclave_integration_tests
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
[ 84%] Built target sgxapp-teaclave_integration_tests
[ 87%] Building unixapp-teaclave_dcap_ref_as
warning: patch for the non root package will be ignored, specify patch at the workspace root:
package:   /teaclave/build/cmake_tomls/unix_app/sdk/rust/Cargo.toml
workspace: /teaclave/build/cmake_tomls/unix_app/Cargo.toml
   Compiling teaclave_dcap_ref_as v0.2.0 (/teaclave/build/cmake_tomls/unix_app/dcap)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.0.rcgu.o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.1.rcgu.o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.10.rcgu.o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.11.rcgu.o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.12.rcgu.o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.13.rcgu.o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.14.rcgu.o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.15.rcgu.o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.2.rcgu.o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.3.rcgu.o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.4.rcgu.o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.5.rcgu.o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.6.rcgu.o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.7.rcgu.o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.8.rcgu.o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.teaclave_dcap_ref_as.42i1rftn-cgu.9.rcgu.o" "-o" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4" "/teaclave/build/target/unix/debug/deps/teaclave_dcap_ref_as-34c1ab047bb4f5e4.2aieksvcbjs5rj13.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/teaclave/build/target/unix/debug/deps" "-L" "/teaclave/build/target/unix/debug/build/ring-fa6a72941b82e68e/out" "-L" "/opt/sgxsdk/lib64" "-L" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-lsgx_dcap_quoteverify" "-lsgx_dcap_ql" "-lsgx_urts" "-Wl,-Bstatic" "/teaclave/build/target/unix/debug/deps/libbase64-2eaf2a28e351c3cf.rlib" "/teaclave/build/target/unix/debug/deps/libpem-cba94910fcf2fbb0.rlib" "/teaclave/build/target/unix/debug/deps/libregex-1d5d7244af3d66e9.rlib" "/teaclave/build/target/unix/debug/deps/libaho_corasick-a0f2b910ddf545ab.rlib" "/teaclave/build/target/unix/debug/deps/libregex_syntax-d8c25f7d5a9c013c.rlib" "/teaclave/build/target/unix/debug/deps/libuuid-a20a61c07a5e6a07.rlib" "/teaclave/build/target/unix/debug/deps/libgetrandom-a0637e0cd9468dd2.rlib" "/teaclave/build/target/unix/debug/deps/libsgx_ucrypto-743039e247033503.rlib" "/teaclave/build/target/unix/debug/deps/librdrand-fe28353969b2b493.rlib" "/teaclave/build/target/unix/debug/deps/librand_core-fe497a007ba4350c.rlib" "/teaclave/build/target/unix/debug/deps/librand_core-7777f623c08783e5.rlib" "/teaclave/build/target/unix/debug/deps/libsgx_types-61793689345b8705.rlib" "/teaclave/build/target/unix/debug/deps/libserde_json-2f471fdd307f4f01.rlib" "/teaclave/build/target/unix/debug/deps/libryu-bc3a68e8fbaa57e5.rlib" "/teaclave/build/target/unix/debug/deps/libitoa-821f48aa9d185ae6.rlib" "/teaclave/build/target/unix/debug/deps/librand-7e628f538e0ee904.rlib" "/teaclave/build/target/unix/debug/deps/librand_chacha-e1bbc9ce737e1c95.rlib" "/teaclave/build/target/unix/debug/deps/libppv_lite86-954a0753d9a936e0.rlib" "/teaclave/build/target/unix/debug/deps/librand_core-7c000a229b20c654.rlib" "/teaclave/build/target/unix/debug/deps/libgetrandom-59ee5384c117d441.rlib" "/teaclave/build/target/unix/debug/deps/libchrono-c103d1cae856a499.rlib" "/teaclave/build/target/unix/debug/deps/libnum_integer-a98c2a89b245908f.rlib" "/teaclave/build/target/unix/debug/deps/libnum_traits-b777a49b81d0f4b1.rlib" "/teaclave/build/target/unix/debug/deps/liblazy_static-cd2401a06b1676f6.rlib" "/teaclave/build/target/unix/debug/deps/librocket-5b8939650bda0b3d.rlib" "/teaclave/build/target/unix/debug/deps/libbinascii-f1c0c15fd8c67cbd.rlib" "/teaclave/build/target/unix/debug/deps/libatty-f44170f0b91b4685.rlib" "/teaclave/build/target/unix/debug/deps/librocket_http-91bccffcaa7d9ffb.rlib" "/teaclave/build/target/unix/debug/deps/libindexmap-4d3fc467064dbc6c.rlib" "/teaclave/build/target/unix/debug/deps/libhashbrown-42875229e1355219.rlib" "/teaclave/build/target/unix/debug/deps/libcookie-671b27d1515c41cd.rlib" "/teaclave/build/target/unix/debug/deps/libbase64-5fe96db873a65d48.rlib" "/teaclave/build/target/unix/debug/deps/libpercent_encoding-bae4c6d884296e4c.rlib" "/teaclave/build/target/unix/debug/deps/libunicode_xid-ac2b5975c21fcd81.rlib" "/teaclave/build/target/unix/debug/deps/libhyper_sync_rustls-5e6fe97572d0ef0a.rlib" "/teaclave/build/target/unix/debug/deps/libwebpki_roots-89b0d65756bad69c.rlib" "/teaclave/build/target/unix/debug/deps/librustls-d17280703a1a3ba1.rlib" "/teaclave/build/target/unix/debug/deps/libbase64-58a43d8f971c44f9.rlib" "/teaclave/build/target/unix/debug/deps/libsct-3d6cead90cd57c24.rlib" "/teaclave/build/target/unix/debug/deps/libwebpki-8b91e6fb81994209.rlib" "/teaclave/build/target/unix/debug/deps/libring-777502481c0443d5.rlib" "/teaclave/build/target/unix/debug/deps/libspin-361d9da1b7a7ce24.rlib" "/teaclave/build/target/unix/debug/deps/libuntrusted-19e0028c5e01f748.rlib" "/teaclave/build/target/unix/debug/deps/libonce_cell-f3b3091a78393424.rlib" "/teaclave/build/target/unix/debug/deps/libsmallvec-0f55f5d6a54014e3.rlib" "/teaclave/build/target/unix/debug/deps/libhyper-c29cc7778ebbd4fb.rlib" "/teaclave/build/target/unix/debug/deps/libmime-68a13591a7a732ab.rlib" "/teaclave/build/target/unix/debug/deps/liblog-34c5ee58e33ce90e.rlib" "/teaclave/build/target/unix/debug/deps/liblanguage_tags-276927bf4664bf5a.rlib" "/teaclave/build/target/unix/debug/deps/libtypeable-6e97b32755d7437e.rlib" "/teaclave/build/target/unix/debug/deps/libtraitobject-0b05b1821ec7acd4.rlib" "/teaclave/build/target/unix/debug/deps/libnum_cpus-3d7d3ee6d089a758.rlib" "/teaclave/build/target/unix/debug/deps/libhttparse-d33c87be2ef50123.rlib" "/teaclave/build/target/unix/debug/deps/libunicase-87e76b15564a1b59.rlib" "/teaclave/build/target/unix/debug/deps/liburl-798f7ac419e14c27.rlib" "/teaclave/build/target/unix/debug/deps/libpercent_encoding-37403a81b788f0c6.rlib" "/teaclave/build/target/unix/debug/deps/libidna-498c795fac0b88d5.rlib" "/teaclave/build/target/unix/debug/deps/libunicode_normalization-1e59d0a601788391.rlib" "/teaclave/build/target/unix/debug/deps/libtinyvec-2a8082d1c3b39837.rlib" "/teaclave/build/target/unix/debug/deps/libtinyvec_macros-a8a3510ab9d2d66d.rlib" "/teaclave/build/target/unix/debug/deps/libunicode_bidi-0fe025d2b861b5b3.rlib" "/teaclave/build/target/unix/debug/deps/libmatches-b31feef5c3ce1062.rlib" "/teaclave/build/target/unix/debug/deps/libtime-75cf3eea65f5d55e.rlib" "/teaclave/build/target/unix/debug/deps/liblibc-5ef8b4f067a22a51.rlib" "/teaclave/build/target/unix/debug/deps/libbase64-40588ebe33f94fcd.rlib" "/teaclave/build/target/unix/debug/deps/libsafemem-452e8a0079ba6078.rlib" "/teaclave/build/target/unix/debug/deps/libbyteorder-4126bddb3356bb8d.rlib" "/teaclave/build/target/unix/debug/deps/libtoml-8c3d5b051ea0ef81.rlib" "/teaclave/build/target/unix/debug/deps/libserde-7c3fd5c68857100f.rlib" "/teaclave/build/target/unix/debug/deps/libtime-2a2f8afe5cff1960.rlib" "/teaclave/build/target/unix/debug/deps/libtime_macros-9b69b5d2fd5d6f47.rlib" "/teaclave/build/target/unix/debug/deps/libstandback-473157be4d2135f4.rlib" "/teaclave/build/target/unix/debug/deps/libmemchr-abe191a7fe2cb81e.rlib" "/teaclave/build/target/unix/debug/deps/libstate-04869b7efe3b9f0e.rlib" "/teaclave/build/target/unix/debug/deps/libyansi-35940f0a6c4fd250.rlib" "/teaclave/build/target/unix/debug/deps/libpear-04c8db12745328ee.rlib" "/teaclave/build/target/unix/debug/deps/liblog-fc223e5a61ef1ec2.rlib" "/teaclave/build/target/unix/debug/deps/libcfg_if-2909e55669d95bfc.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-3010daceac92f8fa.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-eed7c8ea6eea20e8.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-637cb1b53c807e95.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-099cf0af4375543b.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-b5f18e83369ef257.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-3bb19daa4485d5fe.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-5298ab0591e7fb29.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-1bda453aef84d106.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-1532436f783b0405.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-3d12d76f5782439f.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-87f8d20d4e058c86.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-d41f1ff31e4e0f27.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-0d5ea4f2d39b8e27.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-31288459e6a43502.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-c52e5d6301e1bd59.rlib" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-2675a9a46b5cec89.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/nightly-2020-10-25-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-f51baad7bbcb81c4.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: cannot find -lsgx_dcap_quoteverify
          /usr/bin/ld: cannot find -lsgx_dcap_ql
          collect2: error: ld returned 1 exit status

error: aborting due to previous error

error: could not compile `teaclave_dcap_ref_as`

To learn more, run the command again with --verbose.
CMakeFiles/unixapp-teaclave_dcap_ref_as.dir/build.make:57: recipe for target 'CMakeFiles/unixapp-teaclave_dcap_ref_as' failed
make[2]: *** [CMakeFiles/unixapp-teaclave_dcap_ref_as] Error 101
CMakeFiles/Makefile2:1699: recipe for target 'CMakeFiles/unixapp-teaclave_dcap_ref_as.dir/all' failed
make[1]: *** [CMakeFiles/unixapp-teaclave_dcap_ref_as.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by mssun** [comment]
Which docker image are you using?

For DCAP, please use `teaclave/teaclave-build-ubuntu-1804-sgx-dcap-1.11:0.1.5` instead.

**Comment by Lio101** [comment]
I am able to build it with `teaclave-build-ubuntu-1804-sgx-dcap-1.11:0.1.5`, was using `teaclave-build-ubuntu-1804-sgx-2.14:latest ` earlier.
Thanks!
