### ISSUE TITLE
请更新下SDK中远程认证(ue-ra)的代码

### ISSUE THREAD

**Issue by xin201501** [apache/incubator-teaclave#648]
我收到intel邮件提示
>2022年8月16日`DEV Intel® Software Guard Extensions Attestation Service (IAS) API version 3`会结束支持，请尽快升级到version4。

我看到API v4中有些数据结构的定义似乎发生了变化。可以更新下Teaclave SGX SDK中`samplecode`中`ue-ra`的代码并给一些从V3迁移到V4的建议吗，谢谢。

**Comment by mssun** [comment]
你好，关于 Teaclave SGX SDK 的相关问题在相应的 repo 的 issue 中提出，便于 community 进行管理，多谢。
