### ISSUE TITLE
Is there a plan to upgrade teaclave-rust-sdk version to 1.1.4

### ISSUE THREAD

**Issue by itux2** [apache/incubator-teaclave#656]
Is there a plan to upgrade teaclave-rust-sdk version to 1.1.4

**Comment by henrysun007** [comment]
teaclave-rust-sdk comes to version 1.1.5 and also has a [preview version 2.0.0](https://github.com/apache/incubator-teaclave-sgx-sdk/tree/v2.0.0-preview). Do you have any preference for the sdk version?

**Comment by qinkunbao** [comment]
As far as I know, there is no such plan at the moment.

**Comment by henrysun007** [comment]
@qinkunbao Which version do you prefer? Maybe I could spare some time to do the upgrade.

**Comment by henrysun007** [comment]
We have upgraded Teaclave Rust SDK version to 2.0.0. Please have a try. Let us know if you need any help. @itux2
