### ISSUE TITLE
 CI pipeline issue: Code scanning / Analyze cpp (pull_request) 

### ISSUE THREAD

**Issue by mssun** [apache/incubator-teaclave#673]
There is CI pipeline issue: 
Code scanning / Analyze cpp (pull_request)

**Comment by henrysun007** [comment]
The root cause for the failure is that the Intel SGX code cannot be compiled in Ubuntu 22.04. I worked around the failure in https://github.com/apache/incubator-teaclave/pull/666 by not compiling third-party code.
