### ISSUE TITLE
Access control service

### ISSUE THREAD

**Issue by henrysun007** [apache/incubator-teaclave#674]
Although documented in [README](https://github.com/apache/incubator-teaclave/blob/master/services/README.md), the acs is actually not used by management service in the implementation. Why? Do you have any potential improvement towards the acs? Please provide some background information. Thanks.

**Comment by mssun** [comment]
Yes, ACS is designed to be the service to evaluate the access control policy. Using a dedicated service makes the policy evaluation more flexible. However, we didn't have time to integrate with the current ACS. In the current implementation, access control policy is hard coded in the  management service.

**Comment by henrysun007** [comment]
Thanks!
