### ISSUE TITLE
An error occurred while compiling teaclave with docker

### ISSUE THREAD

**Issue by digitalinformation** [apache/incubator-teaclave#708]
![错误](https://github.com/apache/incubator-teaclave/assets/94784449/3ed1c92b-adf8-49f6-b663-8e3fce3d1a50)

-- Submodule update
fatal: detected dubious ownership in repository at '/teaclave'
To add an exception for this directory, call:

git config --global --add safe.directory /teaclave
CMake Error at cmake/TeaclaveUtils.cmake:55 (message):
  git submodule update --init failed with 128, please checkout submodules
Call Stack (most recent call first):
  CMakeLists.txt:52 (init_submodules)

-- Configuring incomplete, errors occurred!
See also "/teaclave/build/CMakeFiles/CMakeOutput.log".

**Comment by digitalinformation** [comment]
The following command also does not work: git config --global --add safe.directory /teaclave

**Comment by henrysun007** [comment]
Can you post the latest error log after calling `git config --global --add safe.directory /teaclave`?

**Comment by digitalinformation** [comment]
您好！
感谢您的帮助
以下是错误信息，麻烦您查收。




就是输入命令git config --global --add safe.directory /teaclave之后没有变化。


网安215464张守恒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-teaclave"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月18日(星期二) 晚上6:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/incubator-teaclave] An error occurred while compiling teaclave with docker (Issue #708)





 
Can you post the latest error log after calling git config --global --add safe.directory /teaclave?

**Comment by digitalinformation** [comment]
Hello, there is no change after entering the command, as follows:
![QQ图片20230718200532](https://github.com/apache/incubator-teaclave/assets/94784449/df65f562-f3b3-4a72-a584-86596ae6b776)
Here are the error logs:
[CMakeOutput.log](https://github.com/apache/incubator-teaclave/files/12080223/CMakeOutput.log)

**Comment by hiroki-chen** [comment]
@digitalinformation I think you need to execute this command inside docker, not on the host machine. You may change the docker command to

```sh
docker run --rm -v $(pwd):/teaclave -w /teaclave \
  -it teaclave/teaclave-build-ubuntu-2004-sgx-2.17.1:0.2.0 \
   bash -c ". /root/.cargo/env && \
     . /opt/sgxsdk/environment && \                        
     mkdir -p build && cd build && \            
     git config --global --add safe.directory '*' && \ # <--- Add this line
     cmake -DTEST_MODE=ON .. && \            
     make -j"
```

or you can enter docker with an interactive shell like bash or something.

BTW, I think the build documentation on the website should be updated.

**Comment by digitalinformation** [comment]
I have solved my problem, thank you very much.
