### ISSUE TITLE
Intel SGX latest support

### ISSUE THREAD

**Issue by marioolf** [apache/incubator-teaclave#723]
Hi, I was wondering if there is any support for the latest versión of Intel SGX 2.22, since I can't find any docker image from any version after 2.17. 

Also, is there any way to build teaclave without the docker image? Should it be working for latest Intel SGX? Or there is just no support from versions newer than 2.17? 

Thanks

**Comment by henrysun007** [comment]
The [Rust SGX SDK](https://github.com/apache/incubator-teaclave-sgx-sdk/tree/v2.0.0-preview) we are using is bounded to the SGX version which is 2.17 in our case. No other version is supported now.

**Comment by volcano0dr** [comment]
The teaclave is using rust-SGX-SDK v2, rust-SGX-SDK v2 is now bound to intel-sgx-sdk 2.17.  We are developing EDMM features for rust-sgx-sdk v2, the EDMM feature code is merged, and we plan to support intel -sgx-sdk 2.21 or newer.

**Comment by volcano0dr** [comment]
The teaclave is using rust-SGX-SDK v2, which is now bound to intel-sgx-sdk 2.17. We are developing EDMM features for rust-sgx-sdk v2 and when the code is merged we will support intel-sgx-sdk 2.21 or higher.

**Comment by marioolf** [comment]
Ok thanks, I will wait for a realease with 2.22 support since it is the version my server is running.
