### ISSUE TITLE
My builtin-functions cannot be invoked by the Python/Rust client SDK

### ISSUE THREAD

**Issue by yujingyue9166** [apache/incubator-teaclave#724]
I tried to add a "builtin-hello-world" function (with the same functionality as the echo example) by following the official documentation at https://teaclave.apache.org/docs/builtin-functions/.

After building with make teaclave_unit_tests and running tests with make run-unit-tests, everything seemed to work normally.

However, when I try to invoke this function using either the Python or Rust client SDKs, I get an error saying the function cannot be found.

I would like to understand:

1. Where can I verify that my builtin-function is correctly registered by the executor?
2. What might be going wrong that is preventing client SDKs from locating and invoking the function?

Any pointers on where to check or how to further troubleshoot this issue would be greatly appreciated! Please let me know if any other details would be helpful in diagnosing the problem.

Thank you for your time and assistance!

**Comment by henrysun007** [comment]
It might be helpful if we could see your modification.

**Comment by yujingyue9166** [comment]
Thank you for replying. These are the main changes I made:
![image](https://github.com/apache/incubator-teaclave/assets/73093539/fc07a02e-3df0-4a02-b294-e877642970fa)
![image](https://github.com/apache/incubator-teaclave/assets/73093539/9b21ad1f-e8f4-4de5-aa2f-74cde3ab7816)
![image](https://github.com/apache/incubator-teaclave/assets/73093539/aa9f8b43-7e93-4d8d-a9f0-8f9d81a91407)
And this is the debug output of running `make teaclave_unit_tests`, `make run-examples` : 
![image](https://github.com/apache/incubator-teaclave/assets/73093539/196ab4c4-116f-4e8f-a332-a09c81abd6a3)

It seems like I am missing some steps after registering the new function.

Could you please advise if any operations needed after function registration and before client invocation? Or help me check if I missed anything in my implementation and debugging steps?

**Comment by yujingyue9166** [comment]
I have found the cause of the problem. I forgot to update the cargo.toml file for the executor.
