### ISSUE TITLE
Support protected_fs in services

### ISSUE THREAD

**Issue by litongxin1991** [apache/incubator-teaclave#79]
Protected_fs is ready but not supported in services.  To support protected_fs in services, following modifications are needed:
1. KMS should support both AEAD and protected_fs keys.
2. RPC messages for KMS should be modified accordingly. 
3. TDFS client should be modified accordingly to save/read files with protected_fs. 

Besides, I am planning to use prost to design KMS RPC messages. 

This issue is related to another issue #60

**Comment by mssun** [comment]
This has been implemented in the `develop` branch, which will be merged into `master` in the near future.
